import nodemailer from "nodemailer";
import { generateReferenceWithTime } from "@/utilities/masterData";

// ── helpers ──────────────────────────────────────────────────────────────────

function row(label, value) {
  if (value === undefined || value === null || value === "") return "";
  return `
    <tr>
      <td style="padding:8px 12px;color:#6b7280;font-size:13px;white-space:nowrap;vertical-align:top;">${label}</td>
      <td style="padding:8px 12px;color:#111827;font-size:13px;font-weight:500;">${value}</td>
    </tr>`;
}

function section(title, rows) {
  return `
    <tr>
      <td colspan="2" style="padding:18px 12px 6px;">
        <div style="font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#7c3aed;border-bottom:1px solid #ede9fe;padding-bottom:6px;">
          ${title}
        </div>
      </td>
    </tr>
    ${rows}`;
}

function buildHtml(data, reference) {
  const {
    selectedSvc,
    commodity, hscode, weight, volume, pieces, packaging, cargoValue, specialHandling,
    origin, destination, pickupType, deliveryType, incoterm, readyDate, frequency,
    selectedAddons,
    cName, cCompany, cEmail, cPhone, cNotes,
    estimate,
  } = data;

  const specialText =
    Array.isArray(specialHandling) && specialHandling.length
      ? specialHandling.join(", ")
      : "None";

  const addonsText =
    Array.isArray(selectedAddons) && selectedAddons.length
      ? selectedAddons.join(", ")
      : "None";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/><title>New Quote Request</title></head>
<body style="margin:0;padding:0;background:#f5f3ff;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f3ff;padding:32px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08);">
        <tr>
          <td colspan="2" style="background:linear-gradient(135deg,#7c3aed,#2563eb);padding:28px 32px;">
            <div style="color:#fff;font-size:22px;font-weight:700;">🚢 New Quote Request</div>
            <div style="color:#ddd6fe;font-size:13px;margin-top:4px;">Reference: <strong style="color:#fff;">${reference}</strong></div>
          </td>
        </tr>
        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
          ${section("Service", row("Service type", selectedSvc))}
          ${section("Cargo Details", [
            row("Commodity", commodity),
            row("HS Code", hscode || "Not provided"),
            row("Weight", weight ? weight + " kg" : "—"),
            row("Volume", volume ? volume + " CBM" : "—"),
            row("Pieces", pieces || "—"),
            row("Packaging", packaging),
            row("Cargo value", cargoValue ? "&#8377; " + Number(cargoValue).toLocaleString("en-IN") : "—"),
            row("Special handling", specialText),
          ].join(""))}
          ${section("Route & Logistics", [
            row("Origin", origin),
            row("Destination", destination),
            row("Pickup type", pickupType),
            row("Delivery type", deliveryType),
            row("Incoterm", incoterm),
            row("Ready date", readyDate),
            row("Frequency", frequency || "One-time"),
          ].join(""))}
          ${section("Add-ons", row("Selected add-ons", addonsText))}
          ${section("Estimate", row("Live estimate", estimate ? "&#8377; " + Number(estimate).toLocaleString("en-IN") : "—"))}
          ${section("Contact Information", [
            row("Full name", cName),
            row("Company", cCompany),
            row("Email", '<a href="mailto:' + cEmail + '" style="color:#7c3aed;">' + cEmail + "</a>"),
            row("Phone / WhatsApp", cPhone),
            row("Notes", cNotes || "—"),
          ].join(""))}
        </table>
        <tr>
          <td colspan="2" style="background:#f9fafb;padding:20px 32px;border-top:1px solid #e5e7eb;">
            <p style="margin:0;font-size:12px;color:#9ca3af;text-align:center;">
              Auto-generated by the Mahaveer Trans quote form.<br/>
              Reply to <a href="mailto:${cEmail}" style="color:#7c3aed;">${cEmail}</a> to follow up.
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ── Route Handler ─────────────────────────────────────────────────────────────

export async function POST(request) {
  try {
    const data = await request.json();
    const reference = generateReferenceWithTime();

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT) || 587,
      secure: Number(process.env.SMTP_PORT) === 465,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const html = buildHtml(data, reference);

    await transporter.sendMail({
      from: `"Mahaveer Trans Quote" <${process.env.SMTP_USER}>`,
      to: process.env.MAIL_TO,
      replyTo: data.cEmail || undefined,
      subject: `[Quote Request] ${reference} — ${data.cName || "New enquiry"} (${data.selectedSvc || "—"})`,
      html,
    });

    return Response.json({ ok: true, reference });
  } catch (err) {
    console.error("[/api/quote] Email send error:", err);
    return Response.json(
      { ok: false, error: err.message || "Failed to send email" },
      { status: 500 }
    );
  }
}
