// Auto-generated by scripts/html-to-nextjs.js
// Edit this file to update page content without touching JSX.

export const SITE_DATA = {
      "meta": {
        "pageTitle": "MahaveerTrans — Modern Logistics",
        "fpTitle": "🎨 Design Settings",
        "fpColorLabel": "Accent Color",
        "fpDisplayLabel": "Display / Heading Font",
        "fpBodyLabel": "Body / UI Font",
        "themeLabel": "☀️ / 🌙 Theme",
        "fontBtnText": "Fonts & Style",
        "drawerFontBtnText": "Fonts & Accent Color",
        "fabIcon": "💬"
      },
      "nav": {
        "brand": "MahaveerTrans Solutions",
        "brandShort": "MahaveerTrans",
        "login": "Log in",
        "cta": "Get Quote →",
        "links": [
          { "label": "Services", "href": "#services" },
          { "label": "About", "href": "#about" },
          { "label": "Fleet", "href": "#fleet" },
          { "label": "Track", "href": "#tracking" },
          { "label": "Reviews", "href": "#testimonials" }
        ],
        "drawerLinks": [
          { "label": "Services", "href": "#services" },
          { "label": "About", "href": "#about" },
          { "label": "Fleet", "href": "#fleet" },
          { "label": "Track Shipment", "href": "#tracking" },
          { "label": "Client Reviews", "href": "#testimonials" },
          { "label": "Get a Quote", "href": "quote.html" }
        ],
        "drawerCta": "Get Free Quote →"
      },
      "company": {
        "name": "MahaveerTrans",
        "tagline": "Delivering the world's goods with precision, speed, and care — your trusted partner in global logistics since 1999.",
        "founded": "2010",
        "phone": "+91 22 4001 8000",
        "email": "hello@MahaveerTrans.com",
        "website": "MahaveerTrans.com",
        "address": "Mumbai, India",
        "rating": "4.9★",
        "ratingLabel": "Average rating across 1,200+ reviews"
      },
      "hero": {
        "pill": "Live tracking across 180+ countries",
        "titleLine1": "Logistics",
        "titleLine2Hl": "Redefined",
        "titleLine3": "For Modern",
        "chip": "2025",
        "description": "End-to-end freight solutions powered by real-time AI routing, live shipment tracking, and a global carrier network built for speed and reliability.",
        "cta1": "Start Shipping →",
        "cta2": "▶ Watch Demo",
        "image": "https://autobahntrucking.com/storage/app/vehicles/images/Bharatbenz-truck-5528TT.jpg",
        "statCard1": {
          "label": "Monthly Deliveries",
          "sub": "shipments this month",
          "badge": "↑ 18% vs last month",
          "capacityLabel": "Capacity used"
        },
        "statCard2": {
          "label": "On-time Rate",
          "sub": "last 200 days"
        },
        "trust": {
          "count": "4,800+",
          "label": "businesses trust MahaveerTrans",
          "avatars": [
            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&q=80&auto=format&fit=crop&crop=face",
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80&auto=format&fit=crop&crop=face",
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&q=80&auto=format&fit=crop&crop=face"
          ]
        },
        "stats": { "shipments": 12400, "onTime": 99 }
      },
      "ticker": ["Air Freight", "Ocean Shipping", "Road Transport", "Cold Chain", "Customs Clearance", "Warehousing & 3PL", "Last Mile Delivery", "Project Cargo", "Express Courier", "Reverse Logistics"],
      "clients": {
        "label": "Trusted by",
        "logos": ["MAHINDRA", "RELIANCE", "INFOSYS", "WIPRO", "ADANI", "GODREJ", "TATA"]
      },
      "services": {
        "sectionTag": "What We Do",
        "heading": "Complete Logistics Under One Roof",
        "headingHl": "Logistics",
        "description": "From a single parcel to a full container — we handle every mode, every route, with zero compromise on visibility.",
        "learnMoreText": "Learn more →",
        "items": [
          { "tag": "Express", "tagClass": "tp-sky", "icon": "✈️", "title": "Air Freight", "description": "Priority air cargo with door-to-door tracking. Partnered with 40+ airlines for daily worldwide departures.", "image": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=80&auto=format&fit=crop" },
          { "tag": "FCL / LCL", "tagClass": "tp-blue", "icon": "🚢", "title": "Sea Freight", "description": "Cost-effective ocean freight across all major trade lanes. Full container or groupage — we handle it all.", "image": "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=600&q=80&auto=format&fit=crop" },
          { "tag": "FTL / LTL", "tagClass": "tp-amber", "icon": "🚛", "title": "Road Transport", "description": "GPS-tracked trucks across the full road network. Temperature-controlled options available nationwide.", "image": "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80&auto=format&fit=crop" },
          { "tag": "3PL", "tagClass": "tp-green", "icon": "🏭", "title": "Warehousing & 3PL", "description": "Smart fulfillment centers with WMS integration, pick & pack, kitting, and same-day dispatch capability.", "image": "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&q=80&auto=format&fit=crop" }
        ]
      },
      "numbers": [
        { "value": 12400, "suffix": "+", "label": "Monthly shipments processed globally" },
        { "value": 99, "suffix": "%", "label": "On-time delivery rate, 90-day avg" },
        { "value": 180, "suffix": "+", "label": "Countries in active network" },
        { "value": 25, "suffix": " yrs", "label": "Years of logistics experience" }
      ],
      "about": {
        "sectionTag": "Our Story",
        "tagStrip": "Since 1999",
        "title": "Built for Scale.",
        "titleHl": "Trusted by All.",
        "p1": "MahaveerTrans was founded in 1999 with a single idea: logistics should be transparent, fast, and accessible to every business. Today we operate in 40+ countries with 3,200 specialists and a proprietary TMS platform that gives clients full supply chain visibility.",
        "p2": "Our AI-powered routing engine selects the best combination of speed, cost, and carbon efficiency for every shipment — automatically optimised in real time.",
        "cta": "Meet The Team →",
        "image": "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=900&q=80&auto=format&fit=crop",
        "features": ["ISO 9001 Certified", "IATA Accredited", "24/7 Control Tower", "AI-Powered Routing", "Carbon Neutral 2030", "Real-time Visibility"]
      },
      "process": {
        "sectionTag": "Simple Process",
        "heading": "Ship in",
        "headingHl": "4 Steps",
        "steps": [
          { "num": "01", "title": "Get a Quote", "desc": "Fill our form in under 60 seconds. Our AI returns an instant, competitive quote for your route." },
          { "num": "02", "title": "We Plan the Route", "desc": "Our team designs the optimal path using AI routing, carrier rates, and customs intelligence." },
          { "num": "03", "title": "Pickup & Transit", "desc": "Your cargo is collected on schedule and moves through our vetted, insured carrier network." },
          { "num": "04", "title": "Delivered ✓", "desc": "Track in real time. Receive photo proof of delivery and full digital documentation." }
        ]
      },
      "fleet": {
        "sectionTag": "Our Fleet",
        "heading": "Built to",
        "headingHl": "Deliver",
        "cta": "View All Fleet →",
        "items": [
          { "title": "Heavy Haulage Fleet", "sub": "200+ trucks across India", "tag": "Road", "tall": true, "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&auto=format&fit=crop" },
          { "title": "Container Vessels", "sub": "40,000+ TEU capacity", "tag": "Ocean", "tall": false, "image": "https://images.unsplash.com/photo-1562408590-e32931084e23?w=500&q=80&auto=format&fit=crop" },
          { "title": "Air Cargo Network", "sub": "40+ airline partners", "tag": "Air", "tall": false, "image": "https://images.unsplash.com/photo-1627579809897-38afb36a8b4c?w=500&q=80&auto=format&fit=crop" },
          { "title": "Smart Warehouses", "sub": "3M sq.ft managed", "tag": "Storage", "tall": false, "image": "https://images.unsplash.com/photo-1553413077-190dd305871c?w=500&q=80&auto=format&fit=crop" },
          { "title": "Urban Delivery Tech", "sub": "EV fleet + drones", "tag": "Last Mile", "tall": false, "image": "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500&q=80&auto=format&fit=crop" }
        ]
      },
      "tracking": {
        "sectionTag": "Real-Time",
        "heading": "Track Your",
        "headingHl": "Shipment",
        "description": "Enter your tracking ID for instant live updates — location, status, customs clearance, and ETA all in one view.",
        "inputPlaceholder": "e.g. VF-2025-00812",
        "btnText": "Track Now",
        "btnFound": "✓ Found!",
        "hints": ["No login needed", "Live map view", "SMS alerts"],
        "demo": {
          "id": "#VF-2025-00812",
          "status": "● In Transit",
          "from": "Mumbai",
          "fromCode": "BOM · Origin",
          "to": "Frankfurt",
          "toCode": "FRA · Destination",
          "timeline": [
            { "status": "done", "title": "Picked up from sender", "time": "May 28 · 09:14 AM" },
            { "status": "done", "title": "Departed Mumbai Airport", "time": "May 28 · 11:40 PM" },
            { "status": "now", "title": "In transit — Dubai layover", "time": "May 29 · 04:22 AM · Now" },
            { "status": "pending", "title": "Arriving Frankfurt", "time": "May 30 · Est. 08:00 AM" }
          ]
        }
      },
      "testimonials": {
        "sectionTag": "Client Stories",
        "heading": "What They",
        "headingHl": "Say",
        "items": [
          { "stars": "★★★★★", "text": "MahaveerTrans cut our import lead time from 3 weeks to 9 days. The tracking platform is genuinely world-class — our ops team loves it.", "name": "Rajesh Mehta", "role": "Supply Chain Director, Tata Consumer", "avatar": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&q=80&auto=format&fit=crop&crop=face" },
          { "stars": "★★★★★", "text": "We handle 500+ shipments monthly across 30 countries. Zero-exception customs handling and brilliant account support sets MahaveerTrans apart.", "name": "Priya Sharma", "role": "Head of Operations, GlobalMed", "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80&auto=format&fit=crop&crop=face" },
          { "stars": "★★★★★", "text": "Cold chain precision is non-negotiable for us. MahaveerTrans's refrigerated fleet and monitoring gave us confidence to expand into five new markets.", "name": "Arjun Kapoor", "role": "CEO, FreshRoute Agri", "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&q=80&auto=format&fit=crop&crop=face" }
        ]
      },
      "cta": {
        "sectionTag": "Get Started",
        "title": "Ready to Ship",
        "titleHl": "Smarter?",
        "description": "Get a free consultation with our experts. No commitment, no hidden fees — just the best logistics solution for your business.",
        "cta1": "Get Free Quote →",
        "cta2": "📞 Call us"
      },
      "footer": {
        "logo": "MahaveerTrans",
        "tagline": "Delivering the world's goods with precision and care. Your trusted logistics partner since 1999.",
        "socials": [
          { "label": "in", "url": "#" },
          { "label": "tw", "url": "#" },
          { "label": "yt", "url": "#" },
          { "label": "ig", "url": "#" }
        ],
        "columns": [
          { "heading": "Services", "links": [["Air Freight", "#"], ["Sea Freight", "#"], ["Road Transport", "#"], ["Warehousing", "#"], ["Cold Chain", "#"], ["Customs", "#"]] },
          { "heading": "Company", "links": [["About Us", "#"], ["Careers", "#"], ["Sustainability", "#"], ["Press", "#"], ["Contact", "#"]] },
          { "heading": "Contact", "links": [["📍 Mumbai, India", "#"], ["📞 +91 22 4001 8000", "#"], ["✉️ hello@MahaveerTrans.com", "#"], ["🌐 MahaveerTrans.com", "#"]] }
        ],
        "copyright": "© 2025 MahaveerTrans Logistics Pvt. Ltd. All rights reserved.",
        "legal": "Privacy · Terms · Sitemap"
      }
    } as const;

export type SiteData = typeof SITE_DATA;
